# Generated by Django 4.1.1 on 2023-02-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customer_image_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('himachal', 'himachal'), ('Assam', 'Assam'), ('kerala', 'kerala'), ('karnataka', 'karnataka'), ('Maharashra', 'Maharashra'), ('Delhi', 'Delhi')], max_length=50),
        ),
    ]
