# Generated by Django 4.1.1 on 2023-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('packed', 'packed'), ('onthe_way', 'on_the_way'), ('delivered', 'delivered'), ('cancel', 'cancel')], default='Pending', max_length=50),
        ),
    ]
